name: dargon2_flutter
description: A wrapper over dargon2 for Flutter application compatibility
version: 2.0.1
homepage: https://github.com/tmthecoder/dargon2_flutter
repository: https://github.com/tmthecoder/dargon2_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dargon2_core:
    git: 'https://github.com/tmthecoder/dargon2_core'
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.tejasmehta.dargon2_flutter
        pluginClass: Dargon2FlutterPlugin
      ios:
        pluginClass: Dargon2FlutterPlugin
