name: dargon2_flutter_mobile
description: The mobile (iOS & Android) platform implementation of dargon2_flutter
version: 3.0.0
homepage: https://github.com/tmthecoder/dargon2_flutter
repository: https://github.com/tmthecoder/dargon2_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dargon2_core: '^2.0.1'
  dargon2_flutter_platform_interface: '^3.0.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: dargon2_flutter
    platforms:
      android:
        dartPluginClass: DArgon2Mobile
      ios:
        dartPluginClass: DArgon2Mobile
