name: dargon2_flutter
description: A Flutter implementation of dargon2, providing Argon2 Password Hashing functionality for mobile & web apps
repository: https://github.com/tmthecoder/dargon2_flutter
homepage: https://github.com/tmthecoder/dargon2_flutter
version: 3.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: dargon2_flutter_mobile
      ios:
        default_package: dargon2_flutter_mobile
      web:
        default_package: dargon2_flutter_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  dargon2_flutter_mobile:
    path: ../dargon2_flutter_mobile
  dargon2_flutter_web:
    path: ../dargon2_flutter_web
  dargon2_flutter_platform_interface: '^3.0.2'



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.3
