name: docbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Generate Documentation
      run: dartdoc
    - name: Push Documentation
      run: |
        cd doc/api
        echo "docs.tmthecoder.dev" > CNAME
        git init
        git config user.name  "Docbot"
        git config user.email "docbot@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/dargon2
        git checkout -b gh-pages
        git add .
        git commit -m "Updated documentation with code from master"
        git push --force secure-origin gh-pages
