name: docbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.x' # you can use 1.12
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - name: Upgrades flutter
      run: flutter upgrade
    - name: Install dependencies
      run: flutter packages get
    - name: Generate Documentation
      run: dartdoc
    - name: Push Documentation
      run: |
        cd doc/api
        echo "docs.tmthecoder.dev" > CNAME
        git init
        git config user.name  "Docbot"
        git config user.email "docbot@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/dargon2_flutter
        git checkout -b gh-pages
        git add .
        git commit -m "Updated documentation with code from master"
        git push --force secure-origin gh-pages
